RockPaperScissors/urls.py
from django.urls import path
from . import views


app_name = 'rockpaperscissors'
urlpatterns = [
    path('', views.index, name='index')
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login_view, name="login"),
    path('register', views.register, name="register"),
    path("logout", views.logout_view, name="logout")
]

madlibs/urls.py
from django.urls import path

from . import views

app_name = 'madlibs'
urlpatterns =[
    path('', views.index, name="index")
]

speed_test/urls.py
from . import views
from django.urls import path

app_name = 'speed_test'
urlpatterns = [
    path('', views.index, name='index'),
    path('type_test', views.type_test, name='type_test'),
    path('equ_solve', views.equ_solve, name='equ_solve')
]

website_01/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('rockpaperscissors/', include('RockPaperScissors.urls')),
    path('madlibs/', include('madlibs.urls')),
    path('speed_test/', include('speed_test.urls'))
]

speed_test/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import fields

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

RockPaperScissors/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.urls.base import reverse

import sys
sys.path.append('..')
from game_01 import rock_paper_scissors as rps
## import rock_paper_scissors as rps


# Create your views here.
def index(request):
    if request.method == "POST":
        choice = request.POST['options']
        i = rps.convert_to_i(choice)
        x = rps.choose_comp()
        comp_choice = rps.display_title(x)
        res = rps.check_win(i, x)
        respo = f"You chose {choice} and the computer chose {comp_choice}: {res}"
        return render(request, 'RockPaperScissors/index.html', {
            "message": respo,
            "result": res
        })
    else:
        return render(request, 'RockPaperScissors/index.html')

home/views.py
from django.contrib.auth import authenticate, login, logout
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.urls.base import reverse
from django.contrib.auth.forms import UserCreationForm

from .forms import CreateUserForm

# Create your views here.
def index(request):
    if not request.user.is_authenticated:     
        return render(request, 'home/index.html')
    else:
        return render(request, 'home/menu.html')

def register(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid:
            try:
                form.save()
                user = authenticate(request, username=request.POST["username"], password=request.POST["password1"]) 
                login(request, user)
                return redirect(reverse('home:index'))
            except:
                message = form.errors
                return render(request, 'home/register.html', {
                "form": form,
                "message": message
            })
    return render(request, 'home/register.html', {
        "form": form
    })


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(reverse('home:index'))
        else:
            message = " Incorrect credentials! Please try again."
            return render(request, "home/login.html", {
                "message": message
            })
    else:
        return render(request, 'home/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'home/index.html')

madlibs/views.py
from django.http.response import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    if request.method == "POST":
        inputs = []

        adj = request.POST["adjective"]
        inputs.append(adj)
        verb1 = request.POST["verb1"]
        inputs.append(verb1)
        verb2 = request.POST["verb2"]
        inputs.append(verb2)
        famous_person = request.POST["famous_person"]
        inputs.append(famous_person)

        for input in inputs:
            if input == "":
                inputs.remove(input)    
        if len(inputs) != 4 :
            result = "Please fill all the form, Thank you!"
        else:
            result = f"Computer programming is so {adj}! It makes me so excited all the time because " \
                     f"I love to {verb1}. Stay positive and {verb2} like you are {famous_person}"
        
        return render(request, "madlibs/index.html", {
            "message": result
        })
    else:
        return render(request, 'madlibs/index.html')

speed_test/views.py
from django.http import HttpResponse
from django.shortcuts import render

import sys
sys.path.append('..')
from game_01 import speed_hands
# imports speed_hands

# Create your views here.
def index(request):
    return render(request, 'speed_test/index.html')


def type_test(request):
    if request.method == "POST":
        
        return render(request, 'speed_test/start_type_test.html')
    else:
        return render(request, 'speed_test/type_test.html')


def equ_solve(request):
    return HttpResponse("Equation solving")

RockPaperScissors/templates/RockPaperScissors/index.html
{% extends 'RockPaperScissors/layout.html' %}

{% block head %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: rgb(27, 37, 39);
        }
        #title {
            color: rgb(208, 255, 0);
            text-align: center;
            margin-top: 10px;
        }
        #form {
            margin: 20px;
        }
        #submit {
            margin-left: 20px;
            margin-top: 20px;
        }
        #message {
            margin-left: 10px;
            margin-right: 10px;
        }
    </style>

    <script>
        document.addEventListener("DOMContentLoaded", function () {

            document.querySelector("#submit").disabled = true;

            document.querySelector("select").onchange = function () {
                document.querySelector("#submit").disabled = false;
            }
        });
    </script>
{% endblock %}


{% block body %}

    <h1 id="title">Rock Paper Scissors</h1>

    <form id="form" action="" method="post">
        {% csrf_token %}
        <select name="options" class="form-select" aria-label="Default select example">
            <option selected>Choose rock, paper or scissors...</option>
            <option value="rock">Rock</option>
            <option value="paper">Paper</option>
            <option value="scissors">Scissors</option>
        </select>
        <input type="submit" id="submit">
    </form>

    {% if result == "You Won!" %}
        <div id="message" class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% elif result == "It's a tie." %}
        <div id="message" class="alert alert-dark" role="alert">
            {{ message }}
        </div>
    {% elif result == "You lost!" %}
        <div id="message" class="alert alert-warning" role="alert">
            {{ message }}
        </div>
    {% endif %}

    <a href="{% url 'home:index' %}">back to menu</a>

{% endblock %}

RockPaperScissors/templates/RockPaperScissors/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Rock Paper Scissors</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

home/templates/home/index.html
{% extends 'home/layout.html' %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
    #title {
        text-align: center;
        font-size: 50px;
        color: black;
        background-color: linen;
    }
    .col-1 {
        background-color: linen;
    }
    .text {
        background-color: linen;
        font-size: 20px;
        margin-top: 20px;
    }
    </style>
{% endblock %}

{% block body %}
    <div id="title">
        Welcome to my game! 
    </div>
    <div class="text">
        Already have and account?                       
        <a href="{% url 'home:login' %}">login</a>
    </div>
    <div class="text">
        New and Dont have an account? Sign in right now for free!
        <a href="{% url 'home:register' %}">register</a>
    </div>
{% endblock %}

home/templates/home/layout.html
<!DOCTYPE html>
<html lang='eng'>
    <head>
        <title>Home</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

home/templates/home/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
		  <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
		</symbol>
	  </svg>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	{% if message %}
		<div class="alert alert-danger d-flex align-items-center" role="alert">
			<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
			<div>
		 		{{ message }}
			</div>	
	  	</div>
	{% endif %}
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'home:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

home/templates/home/menu.html
{% extends 'home/layout.html' %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: rgb(27, 37, 39);
        }
        #title {
            color: rgb(208, 255, 0);
            text-align: center;
            margin-top: 10px;
        }
        .text {
            color:rgb(208, 255, 0)
        }
    </style>
{% endblock %}

{% block body %}
    <h1 id="title">Welcome {{ request.user.username }}!</h1>
    <h2 class="text">This is the menu</h2>
    <ul class="text">
        <li><a href="{% url 'rockpaperscissors:index' %}">Rock Paper Scissors</a></li>
        <li><a href="{% url 'madlibs:index' %}">Madlibs</a></li>
        <li><a href="{% url 'speed_test:index' %}">Speed test</a></li>
        <li>game 4</li>
    </ul>
    <a href="{% url 'home:logout' %}">Logout</a>
{% endblock %}

home/templates/home/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
		  <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
		</symbol>
	  </svg>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	{% if message %}
		<div class="alert alert-danger d-flex align-items-center" role="alert">
			<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
			<div>
		 		{{ message }}
			</div>	
	  	</div>
	{% endif %}
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
		 		<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'home:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

madlibs/templates/madlibs/index.html
{% extends 'madlibs/layout.html' %}

{% block head %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: rgb(27, 37, 39);
        }
        input {
            margin: 10px;
        }
        #title {
            color: rgb(208, 255, 0);
            text-align: center;
            margin-top: 10px;
        }

        #form {
            margin: 20px;
        }

        #submit {
            margin-left: 20px;
            margin-top: 20px;
        }

        #message {
            color: rgb(208, 255, 0);
            margin-left: 10px;
            margin-right: 10px;
        }

        #space {
            margin-top: 10px;
        }
    </style>

{% endblock %}

{% block body %}

    <h1 id="title">Madlibs</h1>
    <form id="form" action="" method="post">
        {% csrf_token %}
        <input type="text" class="form-control" placeholder="adjective" name="adjective">
        <input type="text" class="form-control" placeholder="Verb" name="verb1">
        <input type="text" class="form-control" placeholder="Another verb" name="verb2">
        <input type="text" class="form-control" placeholder="Famous person" name="famous_person">
        <input type="submit" id="submit">
    </form>
    {% if message %}
    <div id="message">
        <h4> {{ message }} </h4>
    </div>
    {% endif %}
    <a href="{% url 'home:index' %}">Back to menu</a>
{% endblock %} 

madlibs/templates/madlibs/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>madlibs</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

speed_test/templates/speed_test/index.html
{% extends 'speed_test/layout.html' %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: rgb(27, 37, 39);
        }
        #title {
            color: rgb(208, 255, 0);
            text-align: center;
            margin-top: 10px;
        }
        .text {
            color:rgb(208, 255, 0);
            margin: 20px;
        }
    </style>
{% endblock %}

{% block body %}
<h1 id="title">Speed test</h1>
<div class="text">
    <ul>
        <li><a href="{% url 'speed_test:type_test' %}">Words</a></li>
        <li><a href="{% url 'speed_test:equ_solve' %}">Equations</a></li>
    </ul>
</div>
<div class="text">
    <a href="{% url 'home:index' %}">back to menu</a>
</div>
{% endblock %}

speed_test/templates/speed_test/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Speed Test</title>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

speed_test/templates/speed_test/start_type_test.html
{% extends 'speed_test/layout.html' %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: rgb(27, 37, 39);
        }
        #title {
            color: rgb(208, 255, 0);
            text-align: center;
            margin-top: 10px;
        }
        #form {
            margin: 20px;
        }
        #submit {
            margin-left: 20px;
            margin-top: 20px;
        }
        .text {
            color:rgb(208, 255, 0);
            margin: 20px;
        }
    </style>
{% endblock %}

{% block body %}
<h1 id="title">Typing test</h1>
<form id="form" action="" method="post">
    {% csrf_token %}
    <input id="submit" type="submit">
</form>
{% endblock %}

speed_test/templates/speed_test/type_test.html
{% extends 'speed_test/layout.html' %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        body {
            background-color: rgb(27, 37, 39);
        }
        #title {
            color: rgb(208, 255, 0);
            text-align: center;
            margin-top: 10px;
        }
        #form {
            margin: 20px;
        }
        #submit {
            margin-left: 20px;
            margin-top: 20px;
        }
        .text {
            color:rgb(208, 255, 0);
            margin: 20px;
        }
    </style>
{% endblock %}

{% block body %}
<h1 id="title">Typing test</h1>
<div class="text">
    <p>When you press submit, the game will start:</p>
    <ol>
        <li>The computer is going to choose a word</li>
        <li>Type the exact same word in the input box</li>
        <li>Press enter when finished</li>
    </ol>
</div>
<form id="foorm" action="{% url 'speed_test:type_test' %}" method="post">
    {% csrf_token %}
    <input id="submit" type="submit">
</form>
{% endblock %}